#include "arrays.hpp"

namespace Global::Arrays {
	ScrollStruct<int> g_Timers[] = {
		{ TranslationString("Unlocked", true), 0 },
		{ TranslationString("100ms", true), 100 },
		{ TranslationString("250ms", true), 250 },
		{ TranslationString("500ms", true), 500 },
		{ TranslationString("750ms", true), 750 },
		{ TranslationString("1s", true), 1000 },
		{ TranslationString("5s", true), 5000 },
		{ TranslationString("10s", true), 10000 },
		{ TranslationString("15s", true), 15000 },
	};

	ScrollStruct<float> g_Distances[] = {
		{ TranslationString("Unlocked", true), 99999.f },
		{ TranslationString("50m", true), 50.f },
		{ TranslationString("100m", true), 100.f },
		{ TranslationString("200m", true), 200.f },
		{ TranslationString("250m", true), 250.f },
		{ TranslationString("300m", true), 300.f },
		{ TranslationString("400m", true), 400.f },
		{ TranslationString("500m", true), 500.f }
	};

	ScrollStruct<uint32_t> g_PedModelPopular[] = {
		{ TranslationString("Alien", true), 0x64611296 },
		{ TranslationString("Astronaut", true), 0xE7B31432 },
		{ TranslationString("Sassy", true), 0x61D4C771 },
		{ TranslationString("Playboy (naked)", true), 0x4498DDE },
		{ TranslationString("Hooker", true), 0x28ABF95 },
		{ TranslationString("Pogo", true), 0xDC59940D },
		{ TranslationString("Stripper", true), 0x52580019 },
		{ TranslationString("Swat", true), 0x8D8F1B10 },
		{ TranslationString("Topless", true), 0x9CF26183 },
		{ TranslationString("Zombie", true), 0xAC4B4506 },
	};

	ScrollStruct<uint32_t> g_PedModelStory[] = {
		{ TranslationString("Michael", true), 0xD7114C9 },
		{ TranslationString("Franklin", true), 0x9B22DBAF },
		{ TranslationString("Trevor", true), 0x9B810FA2 },
		{ TranslationString("Amanda", true), 0x6D1E15F7 },
		{ TranslationString("Ashley", true), 0x7EF440DB },
		{ TranslationString("Brad", true), 0xBDBB4922 },
		{ TranslationString("Chef", true), 0x49EADBF6 },
		{ TranslationString("Chris Formage", true), 0x286E54A7 },
		{ TranslationString("Clag", true), 0x6CCFE08A },
		{ TranslationString("Cletus", true), 0xE6631195 },
		{ TranslationString("Dave Norton", true), 0x15CD4C33 },
		{ TranslationString("Denise", true), 0x820B33BD },
		{ TranslationString("Fabien", true), 0xD090C350 },
		{ TranslationString("Floyd", true), 0xB1B196B2 },
		{ TranslationString("Jay Norris", true), 0x7A32EE74 },
		{ TranslationString("Jimmy", true), 0x570462B9 },
		{ TranslationString("Lamar", true), 0x65B93076 },
		{ TranslationString("Lazlow", true), 0xDFE443E5 },
		{ TranslationString("Lester", true), 0x4DA6E849 },
		{ TranslationString("Mrs Phillips", true), 0x3862EEA8 },
		{ TranslationString("Stretch", true), 0x36984358 },
		{ TranslationString("Tao Cheng", true), 0xDC5C5EA5 },
		{ TranslationString("Tennis Coach", true), 0xA23B5F57 },
		{ TranslationString("Tracy", true), 0xDE352A35 },
		{ TranslationString("Wade", true), 0x92991B72 }
	};

	ScrollStruct<uint32_t> g_PedModelAnimal[] = {
		{ TranslationString("Boar", true), 0xCE5FF074 },
		{ TranslationString("Chimp", true), 0xA8683715 },
		{ TranslationString("Chop", true), 0x14EC17EA },
		{ TranslationString("Cow", true), 0xFCFA9E1E },
		{ TranslationString("Coyote", true), 0x644AC75E },
		{ TranslationString("Crow", true), 0x18012A9F },
		{ TranslationString("Deer", true), 0xD86B5A95 },
		{ TranslationString("Fish", true), 0x2FD800B7 },
		{ TranslationString("Chicken Hawk", true), 0xAAB71F62 },
		{ TranslationString("Hen", true), 0x6AF51FAF },
		{ TranslationString("Husky", true), 0x4E8F95A2 },
		{ TranslationString("Mountain Lion", true), 0x1250D7BA },
		{ TranslationString("Pig", true), 0xB11BAB56 },
		{ TranslationString("Pigeon", true), 0x6A20728 },
		{ TranslationString("Retriever", true), 0x349F33E1 },
		{ TranslationString("Rhesus", true), 0xC2D06F53 },
		{ TranslationString("Rottweiler", true), 0x9563221D },
		{ TranslationString("Seagull", true), 0xD3939DFD },
		{ TranslationString("Tiger Shark", true), 0x6C3F072 },
		{ TranslationString("Shepherd", true), 0x431FC24C },
	};

	ScrollStruct<uint32_t> g_PedModelEmergency[] = {
		{ TranslationString("Black Ops", true), 0xB3F3EE34 },
		{ TranslationString("Chem Security", true), 0x2EFEAFD5 },
		{ TranslationString("City Cop", true), 0x5E3DA4A4 },
		{ TranslationString("County Cop", true), 0x9AB35F63 },
		{ TranslationString("Fireman", true), 0xB6B1EDA8 },
		{ TranslationString("Security Guard", true), 0x709220C7 },
		{ TranslationString("Highway Cop", true), 0x739B1EF5 },
		{ TranslationString("Lifeguard", true), 0xB4A6862 },
		{ TranslationString("Marine", true), 0x72C0CAD2 },
		{ TranslationString("Marine (Senior)", true), 0xF0259D83 },
		{ TranslationString("Paramedic", true), 0xB353629E },
		{ TranslationString("Ranger", true), 0xEF7135AE },
		{ TranslationString("Prison Guard", true), 0x56C96FC6 },
		{ TranslationString("Security Guard", true), 0xD768B228 },
		{ TranslationString("Sheriff", true), 0xB144F9B9 },
		{ TranslationString("Snow Cop", true), 0x1AE8BB58 },
	};

	ScrollStruct<uint32_t> g_PedModelRole[] = {
		{ TranslationString("Bouncer", true), 0x9FD4292D },
		{ TranslationString("Bride", true), 0x6162EC47 },
		{ TranslationString("Pest Control", true), 0x48114518 },
		{ TranslationString("Doctor", true), 0xD47303AC },
		{ TranslationString("Factory Worker", true), 0x4163A158 },
		{ TranslationString("Garbage Man", true), 0xEE75A00F },
		{ TranslationString("Groom", true), 0xFECE8B85 },
		{ TranslationString("Hunter", true), 0xCE1324DE },
		{ TranslationString("Jesus", true), 0xCE2CB751 },
		{ TranslationString("Mime", true), 0x3CDCA742 },
		{ TranslationString("Priest", true), 0x6437E77D },
		{ TranslationString("Prisoner", true), 0xB1BB9B59 },
		{ TranslationString("Scientist", true), 0x4117D39B },
		{ TranslationString("Spy", true), 0x5B81D86C },
	};

	ScrollStruct<uint32_t> g_PedModelAmbient[] = {
		{ TranslationString("Body Builder", true), 0xDA116E7E },
		{ TranslationString("Nonce", true), 0x7DC3908F },
		{ TranslationString("Guido", true), 0xC6B49A2F },
		{ TranslationString("Statue", true), 0x795AC7A8 },
		{ TranslationString("Mani", true), 0xC8BB1E52 },
		{ TranslationString("Griff", true), 0xC454BCBB },
	};

	ScrollStruct<uint32_t> g_PedModelMisc[] = {
		{ TranslationString("Dead Hooker", true), 0x73DEA88B },
		{ TranslationString("Imporage", true), 0x348065F5 },
		{ TranslationString("Marston", true), 0x38430167 },
		{ TranslationString("Misty", true), 0xD128FF9D },
		{ TranslationString("Niko", true), 0xEEDACFC9 },
	};

	ScrollStruct<int> g_PedBones[] = {
		{ TranslationString("Head", true), 31086 },
		{ TranslationString("Neck", true), 39317 },
		{ TranslationString("Chest", true), 24818 },
		{ TranslationString("Right Hand", true), 57005 }, // 28422
		{ TranslationString("Left Hand", true), 18905 }, // 36029
		{ TranslationString("Right Foot", true), 52301 }, // 6286
		{ TranslationString("Left Foot", true), 14201 },
		{ TranslationString("Right Calf", true), 36864 },
		{ TranslationString("Left Calf", true), 63931 },
		{ TranslationString("Right Forearm", true), 28252 },
		{ TranslationString("Left Forearm", true), 61163 },
		{ TranslationString("Right Upper Arm", true), 40269 },
		{ TranslationString("Left Upper Arm", true), 45509 }
	};

	ScrollStruct<const char*> g_VehicleBones[] = {
		{ TranslationString("Front: Left Wheel", true), "wheel_lf" },
		{ TranslationString("Front: Right Wheel", true), "wheel_rf" },
		{ TranslationString("Rear: Left Wheel", true), "wheel_lr" },
		{ TranslationString("Rear: Right Wheel", true), "wheel_rr" },
		{ TranslationString("Left: Tail Light", true), "taillight_l" },
		{ TranslationString("Left: Headlight", true), "headlight_l" },
		{ TranslationString("Right: Tail Light", true), "taillight_r" },
		{ TranslationString("Right: Headlight", true), "headlight_r" },
		{ TranslationString("Numberplate", true), "numberplate" },
		{ TranslationString("Exhaust", true), "exhaust" }
	};

	ScrollStruct<Particle> g_Particles[] = {
		{ TranslationString("Purple Cloud 1", true), { "scr_rcbarry2", "scr_clown_appears", false } },
		{ TranslationString("Purple Cloud 2", true), { "scr_rcbarry2", "scr_clown_death", false } },
		{ TranslationString("Purple Cloud 3", true), { "scr_rcbarry2", "scr_exp_clown", false } },
		{ TranslationString("Firework Starburst", true), { "scr_indep_fireworks", "scr_indep_firework_starburst", false } },
		{ TranslationString("Firework Fountain", true), { "scr_indep_fireworks", "scr_indep_firework_fountain", false } },
		{ TranslationString("Firework Shotburst", true), { "scr_indep_fireworks", "scr_indep_firework_shotburst", false } },
		{ TranslationString("Xmas Firework Burst", true), { "proj_xmas_firework", "scr_firework_xmas_spiral_burst_rgw", false } },
		{ TranslationString("Teleport", true), { "scr_rcbarry1", "scr_alien_teleport", false } },
		{ TranslationString("Disintegration", true), { "scr_rcbarry1", "scr_alien_disintegrate", false } },
		{ TranslationString("Drip", true), { "scr_agencyheist", "scr_fbi_mop_drips", false } },
		{ TranslationString("Flower Jet", true), { "scr_rcbarry2", "scr_clown_bul", false } },
		{ TranslationString("Flash", true), { "scr_rcpaparazzo1", "scr_rcpap1_camera", false } },
		{ TranslationString("Blue Flash", true), { "scr_rcbarry1", "scr_alien_impact_bul", false } },
		{ TranslationString("Burnout", true), { "scr_recartheft", "scr_wheel_burnout", false } },
		{ TranslationString("Splash", true), { "scr_trevor1", "scr_trev1_trailer_splash", false } },
		{ TranslationString("Blood", true), { "scr_solomon3", "scr_trev4_747_blood_impact", false } },
		{ TranslationString("Sparks", true), { "scr_family4", "scr_fam4_trailer_sparks", false } },
		{ TranslationString("Shock", true), { "scr_trevor1", "scr_trev1_trailer_boosh", false } },
		{ TranslationString("Money Cloud", true), { "scr_ornate_heist", "scr_heist_ornate_banknotes", false } },
		{ TranslationString("Tire Smoke", true), { "scr_carsteal4", "scr_carsteal4_wheel_burnout", false } },
		{ TranslationString("Clouds", true), { "wpn_projectile", "proj_missile_trail", true } },
		{ TranslationString("Golf Trail", true), { "scr_minigamegolf", "scr_golf_ball_trail", true } },
		{ TranslationString("Tennis Trail", true), { "scr_minigametennis", "scr_tennis_ball_trail", true } },
		{ TranslationString("Water Trail", true), { "core", "trail_splash_water", true } },
		{ TranslationString("Parachute Trail", true), { "core", "ped_parachute_trail", true } },
		{ TranslationString("Flare Trail", true), { "core", "proj_flare_trail", true } },
		{ TranslationString("Blood Trail", true), { "core", "trail_splash_blood", true } },
		{ TranslationString("Grenade Trail", true), { "wpn_projectile", "proj_grenade_trail", true } },
		{ TranslationString("Flaregun Trail", true), { "wpn_projectile", "proj_flare_trail", true } },
	};

	ScrollStruct<uint32_t> g_Weapons[] = {
		{ TranslationString("Pistol", true), 0x1b06d571 },
		{ TranslationString("Pistol Mk II", true), 0xbfe256d4 },
		{ TranslationString("Combat Pistol", true), 0x5ef9fec4 },
		{ TranslationString("AP Pistol", true), 0x22d8fe39 },
		{ TranslationString("Stun Gun", true), 0x3656c8c1 },
		{ TranslationString("Pistol .50", true), 0x99aeeb3b },
		{ TranslationString("SNS Pistol", true), 0xbfd21232 },
		{ TranslationString("SNS Pistol Mk II", true), 0x88374054 },
		{ TranslationString("Heavy Pistol", true), 0xd205520e },
		{ TranslationString("Vintage Pistol", true), 0x83839c4 },
		{ TranslationString("Flare Gun", true), 0x47757124 },
		{ TranslationString("Marksman Pistol", true), 0xdc4db296 },
		{ TranslationString("Heavy Revolver", true), 0xc1b3c3d1 },
		{ TranslationString("Heavy Revolver Mk II", true), 0xcb96392f },
		{ TranslationString("Double Action Revolver", true), 0x97ea20b8 },
		{ TranslationString("Up-n-Atomizer", true), 0xaf3696a1 },
		{ TranslationString("Ceramic Pistol", true), 0x2b5ef5ec },
		{ TranslationString("Navy Revolver", true), 0x917f6c8c },
		{ TranslationString("Gadget Pistol", true), 0x57a4368c },

		{ TranslationString("Micro SMG", true), 0x13532244 },
		{ TranslationString("SMG", true), 0x2be6766b },
		{ TranslationString("SMG Mk II", true), 0x78a97cd0 },
		{ TranslationString("Assault SMG", true), 0xefe7e2df },
		{ TranslationString("Combat PDW", true), 0xa3d4d34 },
		{ TranslationString("Machine Pistol", true), 0xdb1aa450 },
		{ TranslationString("Mini SMG", true), 0xbd248b55 },
		{ TranslationString("Unholy Hellbringer", true), 0x476bf155 },

		{ TranslationString("Pump Shotgun", true), 0x1d073a89 },
		{ TranslationString("Pump Shotgun Mk II", true), 0x555af99a },
		{ TranslationString("Sawed-Off Shotgun", true), 0x7846a318 },
		{ TranslationString("Assault Shotgun", true), 0xe284c527 },
		{ TranslationString("Bullpup Shotgun", true), 0x9d61e50f },
		{ TranslationString("Musket", true), 0xa89cb99e },
		{ TranslationString("Heavy Shotgun", true), 0x3aabbbaa },
		{ TranslationString("Double Barrel Shotgun", true), 0xef951fbb },
		{ TranslationString("Sweeper Shotgun", true), 0x12e82d3d },
		{ TranslationString("Combat Shotgun", true), 0x5a96ba4 },

		{ TranslationString("Assault Rifle", true), 0xbfefff6d },
		{ TranslationString("Assault Rifle Mk II", true), 0x394f415c },
		{ TranslationString("Carbine Rifle", true), 0x83bf0278 },
		{ TranslationString("Carbine Rifle Mk II", true), 0xfad1f1c9 },
		{ TranslationString("Advanced Rifle", true), 0xaf113f99 },
		{ TranslationString("Special Carbine", true), 0xc0a3098d },
		{ TranslationString("Special Carbine Mk II", true), 0x969c3d67 },
		{ TranslationString("Bullpup Rifle", true), 0x7f229f94 },
		{ TranslationString("Bullpup Rifle Mk II", true), 0x84d6fafd },
		{ TranslationString("Compact Rifle", true), 0x624fe830 },
		{ TranslationString("Military Rifle", true), 0x9d1f17e6 },

		{ TranslationString("MG", true), 0x9d07f764 },
		{ TranslationString("Combat MG", true), 0x7fd62962 },
		{ TranslationString("Combat MG Mk II", true), 0xdbbd7280 },
		{ TranslationString("Gusenberg Sweeper", true), 0x61012683 },

		{ TranslationString("Sniper Rifle", true), 0x5fc3c11 },
		{ TranslationString("Heavy Sniper", true), 0xc472fe2 },
		{ TranslationString("Heavy Sniper Mk II", true), 0xa914799 },
		{ TranslationString("Marksman Rifle", true), 0xc734385a },
		{ TranslationString("Marksman Rifle Mk II", true), 0x6a6c02e0 },

		{ TranslationString("RPG", true), 0xb1ca77b1 },
		{ TranslationString("Grenade Launcher", true), 0xa284510b },
		{ TranslationString("Grenade Launcher Smoke", true), 0x4dd2dc56 },
		{ TranslationString("Minigun", true), 0x42bf8a85 },
		{ TranslationString("Firework Launcher", true), 0x7f7497e5 },
		{ TranslationString("Railgun", true), 0x6d544c99 },
		{ TranslationString("Homing Launcher", true), 0x63ab0442 },
		{ TranslationString("Compact Grenade Launcher", true), 0x781fe4a },
		{ TranslationString("Widowmaker", true), 0xb62d1f67 },

		{ TranslationString("Jerry Can", true), 0x34a67b97 },
		{ TranslationString("Hazardous Jerry Can", true), 0xba536372 },
		{ TranslationString("Parachute", true), 0xfbab5776 },
		{ TranslationString("Fire Extinguisher", true), 0x60ec506 },
		{ TranslationString("Digi Scanner", true), 0xfdbadced },

		{ TranslationString("Grenade", true), 0x93e220bd },
		{ TranslationString("BZ Gas", true), 0xa0973d5e },
		{ TranslationString("Molotov Cocktail", true), 0x24b17070 },
		{ TranslationString("Sticky Bomb", true), 0x2c3731d9 },
		{ TranslationString("Proximity Mines", true), 0xab564b93 },
		{ TranslationString("Snowballs", true), 0x787f0bb },
		{ TranslationString("Pipe Bombs", true), 0xba45e8b8 },
		{ TranslationString("Baseball", true), 0x23c9f95c },
		{ TranslationString("Tear Gas", true), 0xfdbc8a50 },
		{ TranslationString("Flare", true), 0x497facc3 },

		{ TranslationString("Antique Cavalry Dagger", true), 0x92a27487 },
		{ TranslationString("Baseball Bat", true), 0x958a4a8f },
		{ TranslationString("Broken Bottle", true), 0xf9e6aa4b },
		{ TranslationString("Crowbar", true), 0x84bd7bfd },
		{ TranslationString("Flashlight", true), 0x8bb05fd7 },
		{ TranslationString("Golf Club", true), 0x440e4788 },
		{ TranslationString("Hammer", true), 0x4e875f73 },
		{ TranslationString("Hatchet", true), 0xf9dcbf2d },
		{ TranslationString("Brass Knuckles", true), 0xd8df3c3c },
		{ TranslationString("Knife", true), 0x99b507ea },
		{ TranslationString("Machete", true), 0xdd5df8d9 },
		{ TranslationString("Switchblade", true), 0xdfe37640 },
		{ TranslationString("Nightstick", true), 0x678b81b1 },
		{ TranslationString("Pipe Wrench", true), 0x19044ee0 },
		{ TranslationString("Battle Axe", true), 0xcd274149 },
		{ TranslationString("Pool Cue", true), 0x94117305 },
		{ TranslationString("Stone Hatchet", true), 0x3813fc08 },
	};

	ScrollStruct<ExplosionTypes> g_Explosions[] = {
		{ TranslationString("Grenade", true), EXPLOSION_GRENADE },
		{ TranslationString("Grenade Launcher", true), EXPLOSION_GRENADELAUNCHER },
		{ TranslationString("Sticky Bomb", true), EXPLOSION_STICKYBOMB },
		{ TranslationString("Molotov", true), EXPLOSION_MOLOTOV },
		{ TranslationString("Rocket", true), EXPLOSION_ROCKET },
		{ TranslationString("Tank Shell", true), EXPLOSION_TANKSHELL },
		{ TranslationString("Hi-Octane", true), EXPLOSION_HI_OCTANE },
		{ TranslationString("Car", true), EXPLOSION_CAR },
		{ TranslationString("Plane", true), EXPLOSION_PLANE },
		{ TranslationString("Petrol Pump", true), EXPLOSION_PETROL_PUMP },
		{ TranslationString("Bike", true), EXPLOSION_BIKE },
		{ TranslationString("Steam", true), EXPLOSION_DIR_STEAM },
		{ TranslationString("Flame", true), EXPLOSION_DIR_FLAME },
		{ TranslationString("Water Hydrant", true), EXPLOSION_DIR_WATER_HYDRANT },
		{ TranslationString("Gas Fire", true), EXPLOSION_DIR_GAS_CANISTER },
		{ TranslationString("Boat", true), EXPLOSION_BOAT },
		{ TranslationString("Ship Destroy", true), EXPLOSION_SHIP_DESTROY },
		{ TranslationString("Truck", true), EXPLOSION_TRUCK },
		{ TranslationString("Bullet", true), EXPLOSION_BULLET },
		{ TranslationString("Smoke Grenade Launcher", true), EXPLOSION_SMOKEGRENADELAUNCHER },
		{ TranslationString("Smoke Grenade", true), EXPLOSION_SMOKEGRENADE },
		{ TranslationString("Bz Gas", true), EXPLOSION_BZGAS },
		{ TranslationString("Flare", true), EXPLOSION_FLARE },
		{ TranslationString("Gas Canister", true), EXPLOSION_GAS_CANISTER },
		{ TranslationString("Extinguisher", true), EXPLOSION_EXTINGUISHER },
		{ TranslationString("Programmable AR", true), EXPLOSION_PROGRAMMABLEAR },
		{ TranslationString("Train", true), EXPLOSION_TRAIN },
		{ TranslationString("Barrel", true), EXPLOSION_BARREL },
		{ TranslationString("Propane", true), EXPLOSION_PROPANE },
		{ TranslationString("Blimp", true), EXPLOSION_BLIMP },
		{ TranslationString("Flame Explode", true), EXPLOSION_DIR_FLAME_EXPLODE },
		{ TranslationString("Tanker", true), EXPLOSION_TANKER },
		{ TranslationString("Plane Rocket", true), EXPLOSION_PLANE_ROCKET },
		{ TranslationString("Vehicle Bullet", true), EXPLOSION_VEHICLE_BULLET },
		{ TranslationString("Gas Tank", true), EXPLOSION_GAS_TANK },
		{ TranslationString("Bird Crap", true), EXPLOSION_BIRD_CRAP },
	};

	ScrollStruct<float> g_Gravity[] = {
		{ TranslationString("Earth", true), 9.807f },
		{ TranslationString("Moon", true), 1.62f },
		{ TranslationString("Mercury", true), 3.7f },
		{ TranslationString("Jupiter", true), 24.79f },
		{ TranslationString("Mars", true), 3.711f },
		{ TranslationString("Saturn", true), 10.44f },
		{ TranslationString("Uranus/Venus", true), 8.87f },
		{ TranslationString("Neptune", true), 11.15f },
		{ TranslationString("Sun", true), 274.0f },
	};

	ScrollStruct<int> g_Opacity[] = {
		{ TranslationString("0%", true), 0 },
		{ TranslationString("20%", true), 51 },
		{ TranslationString("40%", true), 102 },
		{ TranslationString("60%", true), 153 },
		{ TranslationString("80%", true), 204 },
		{ TranslationString("100%", true), 255 }
	};

	ScrollStruct<uint32_t> g_VehicleWeapons[] = {
		{ TranslationString("RPG", true), 0xb1ca77b1 },
		{ TranslationString("Snowball", true), 0x787F0BB },
		{ TranslationString("Firework", true), 0x7f7497e5 },
		{ TranslationString("Flare", true), 0x497FACC3 },
		{ TranslationString("Player Laser", true), 0xeffd014b },
		{ TranslationString("Enemy Laser", true), 0x5d6660ab },
		{ TranslationString("Space Rocket", true), 0xf8a3939f },
		{ TranslationString("Player Bullet", true), 0x4b139b2d },
		{ TranslationString("Player Buzzard", true), 0x46b89c8e },
	};

	ScrollStruct<std::pair<Math::Vector3_<float>, Math::Vector3_<float>>> g_Acrobatics[] = {
		{ TranslationString("Wheelie", true), { { 0.f, 0.f, 1.f }, { 0.f, 5.0f, 0.f } } },
		{ TranslationString("Kickflip", true), { { 0.f, 0.0f, 11.5f }, { 5.f, 0.f, 0.f } } },
		{ TranslationString("Double Kickflip", true), { { 0.f, 0.0f, 21.f }, { 10.f, 0.f, 0.f } } },
		{ TranslationString("Quadruple Kickflip", true), {{ 0.f, 0.0f, 33.f }, { 15.f, 0.f, 0.f } } },
		{ TranslationString("Leap", true), {{ 0.f, 0.f, 20.f }, { 0.f, 0.f, 0.f } } },
		{ TranslationString("Slingshot", true), {{ 0.f, 0.f, 200.f }, { 0.f, 0.f, 0.f } } },
		{ TranslationString("Backflip", true), {{ 0.f, 0.f, 15.5f }, { 0.f, 1.3f, 0.f } } },
		{ TranslationString("Frontflip", true), {{ 0.f, 0.f, 15.5f }, { 0.f, -1.f, 0.f } } },
		{ TranslationString("Right Jump", true), {{ 0.f, 0.f, 2.8f }, { -3.f, 0.f, 0.f } } },
		{ TranslationString("Left Jump", true), {{ 0.f, 0.f, 2.8f }, { 3.f, 0.f, 0.f } } }
	};

	ScrollStruct<Math::Vector3_<float>> g_PopularLocations[] = {
		{ TranslationString("Diamond Casino", true), {919.94f, 50.7f, 80.90f } },
		{ TranslationString("Los Santos Customs", true), {-365.425f, -131.809f, 37.873f } },
		{ TranslationString("Los Santos Airport", true), {-1052.392f, -2933.508f, 13.951f } },
		{ TranslationString("Sandy Shores Airfield", true), {1770.241f, 3266.942f, 41.620f } },
		{ TranslationString("Eclipse Towers", true), {-807.247f, 301.868f, 86.073f } },
		{ TranslationString("Eclipse Towers Garage (Outside)", true), {-795.46f, 308.89f, 85.71f } },
		{ TranslationString("Eclipse Towers Roof", true), {-779.026f, 331.695f, 238.828f } },
		{ TranslationString("Fort Zancudo", true), {-2119.877f, 3284.521f, 32.810f } },
		{ TranslationString("Mount Chiliad", true), {498.142f, 5593.435f, 795.364f } },
		{ TranslationString("Michael's House", true), {-803.462f, 172.808f, 72.845f } },
		{ TranslationString("Franklin's House", true), {0.603f, 527.954f, 174.628f } },
		{ TranslationString("Lester's House", true), {1273.727f, -1712.099f, 54.771f } },
		{ TranslationString("Trevor's Meth Lab", true), {1393.173f, 3602.266f, 38.942f } },
		{ TranslationString("Floyd's Apartment", true), {-1159.055f, -1520.858f, 10.633f } },
		{ TranslationString("Prison", true), {1678.585f, 2513.168f, 45.565f } },
		{ TranslationString("Torture Room", true), {144.672f, -2201.973f, 4.688f } },
		{ TranslationString("Del Perro Beach", true), {-1583.278f, -1099.167f, 4.956f } },
		{ TranslationString("Del Perro Pier", true), {-1731.210f, -1110.329f, 13.102f } },
		{ TranslationString("Helicopter Pad", true), {-724.384f, -1443.399f, 5.001f } },
		{ TranslationString("Maze Bank", true), {-75.858f, -817.789f, 326.174f } },
		{ TranslationString("FIB Building", true), {135.786f, -749.233f, 258.152f } },
		{ TranslationString("IAA Office", true), {121.282f, -622.149f, 206.047f } },
		{ TranslationString("Blaine County Bank", true), {-108.245f, 6466.301f, 31.627f } },
		{ TranslationString("Pacific Standard Vault", true), {256.786f, 226.157f, 101.876f } },
		{ TranslationString("Humane Labs", true), {3616.195f, 3738.724f, 28.690f } },
		{ TranslationString("Humane Labs Tunnel", true), {3524.949f, 3708.167f, 20.992f } },
		{ TranslationString("Playboy Mansion", true), {-1461.834f, 179.259f, 54.752f } },
		{ TranslationString("Mors Mutual Insurance", true), {-232.084f, -1163.830f, 22.948f } },
		{ TranslationString("Impound Lot", true), {401.057f, -1631.766f, 29.293f } },
		{ TranslationString("Police Station", true), {441.259f, -983.160f, 30.690f } },
		{ TranslationString("Underwater UFO", true), {763.656f, 7381.180f, -110.135f } },
		{ TranslationString("Vinewood Sign", true), {741.941f, 1198.555f, 326.344f } },
		{ TranslationString("Waterfall", true), {-597.9525f, 4475.2910f, 25.6890f } },
		{ TranslationString("Island", true), {20.968f, 7636.292f, 15.943f } },
		{ TranslationString("Bank Vault", true), { 255.5819f, 217.6896f, 101.6834f }}
	};

	ScrollStruct<uint32_t> g_ObjectModelSmall[] = {
		{ TranslationString("Alarm", true), 0x9E5FFFCB },
		{ TranslationString("Backpack", true), 0x47B7DAED },
		{ TranslationString("Barbell", true), 0xE2FBA8D8 },
		{ TranslationString("Basketball", true), 0x6DB9599A },
		{ TranslationString("Beachball", true), 0x81ECE1F },
		{ TranslationString("Bear 1", true), 0x772114C9 },
		{ TranslationString("Bear 2", true), 0x3CF34F26 },
		{ TranslationString("Bigfoot Mask", true), 0xC9751EF7 },
		{ TranslationString("Bong", true), 0xF0A61994 },
		{ TranslationString("Campfire", true), 0xC079B265 },
		{ TranslationString("Candle", true), 0x203011A1 },
		{ TranslationString("Dildo", true), 0xE6CB661E },
		{ TranslationString("Dog Cage", true), 0x16A39A90 },
		{ TranslationString("Egg", true), 0x6B795EBC },
		{ TranslationString("EMP", true), 0x3794ACC9 },
		{ TranslationString("Engine", true), 0xDD75614 },
		{ TranslationString("Fish", true), 0xCE3D7AA0 },
		{ TranslationString("Gold", true), 0xF046EA37 },
		{ TranslationString("Guitar 1", true), 0xD5C0BC07 },
		{ TranslationString("Guitar 2", true), 0xA4E7E0A7 },
		{ TranslationString("Hotdog", true), 0x98EE1ACD },
		{ TranslationString("Katana", true), 0xE2BA016F },
		{ TranslationString("Lawnmower", true), 0x1AB39621 },
		{ TranslationString("Leafblower", true), 0x5F989485 },
		{ TranslationString("Minigun", true), 0xC89630B8 },
		{ TranslationString("Missile", true), 0xB2274905 },
		{ TranslationString("Parachute", true), 0x34DCF0A3 },
		{ TranslationString("Pumpkin", true), 0x83C07621 },
		{ TranslationString("Safe", true), 0x40F52369 },
		{ TranslationString("Saxophone", true), 0x1212FE11 },
		{ TranslationString("Scuba Tank", true), 0x18B8F776 },
		{ TranslationString("Shield", true), 0x44083A8F },
		{ TranslationString("Shit", true), 0x84898EFE },
		{ TranslationString("Soccer Ball", true), 0xD541462D },
		{ TranslationString("Toilet", true), 0x6F9939C7 },
		{ TranslationString("Traffic Cone", true), 0xE0264F5D },
		{ TranslationString("TV", true), 0x5C9F1C35 },
		{ TranslationString("Volleyball", true), 0xC79A987E },
		{ TranslationString("Weed", true), 0x1AFA6A0A },
	};

	ScrollStruct<uint32_t> g_ObjectModelMedium[] = {
		{ TranslationString("Anti-Aircraft", true), 0x98D3236B },
		{ TranslationString("Arcade", true), 0xA50DDDD0 },
		{ TranslationString("Bed", true), 0xB374CC1F },
		{ TranslationString("Bench", true), 0x6BA514AC },
		{ TranslationString("Blast Fence", true), 0xB4978950 },
		{ TranslationString("Block", true), 0xC3F13FCC },
		{ TranslationString("Bumper Car", true), 0xFB631122 },
		{ TranslationString("Cheetah", true), 0x37D80B0E },
		{ TranslationString("Dinghy", true), 0x282D6851 },
		{ TranslationString("Entity XF", true), 0xB155FD87 },
		{ TranslationString("Ferris Car", true), 0x1AFA509F },
		{ TranslationString("Helicopter", true), 0x8E8C7A5B },
		{ TranslationString("JB700", true), 0x72F54E90 },
		{ TranslationString("Jetski Ramp", true), 0xBF8918DE },
		{ TranslationString("Log", true), 0xACD6D1AB },
		{ TranslationString("Mannequin", true), 0x7FFBC1E2 },
		{ TranslationString("Orange Sphere", true), 0x8DA1C0E },
		{ TranslationString("Propeller", true), 0x5D20643D },
		{ TranslationString("Ramp 1", true), 0xB157C9E4 },
		{ TranslationString("Ramp 2", true), 0xF4F1511E },
		{ TranslationString("Ramp 3", true), 0x93948E5E },
		{ TranslationString("Repair", true), 0xE6FA7770 },
		{ TranslationString("Sand Block", true), 0xF724026D },
		{ TranslationString("Sofa", true), 0x5EF5520E },
		{ TranslationString("Stairs", true), 0x757C28D },
		{ TranslationString("Umbrella", true), 0xDCA9A809 },
		{ TranslationString("Xmas Tree", true), 0xE3BA450 },
	};

	ScrollStruct<uint32_t> g_ObjectModelLarge[] = {
		{ TranslationString("Asteroid", true), 0xDF9841D7 },
		{ TranslationString("Barge 1", true), 0x9C762726 },
		{ TranslationString("Barge 2", true), 0x8AF58425 },
		{ TranslationString("Cablecar", true), 0xD44295DD },
		{ TranslationString("Crane", true), 0x7D10B85C },
		{ TranslationString("Crane Cab", true), 0x3673E396 },
		{ TranslationString("Ferris Wheel", true), 0xC42C019A },
		{ TranslationString("Halfpipe", true), 0xF66F582F },
		{ TranslationString("Jet", true), 0xC2BC19CD },
		{ TranslationString("Lava", true), 0xD733DF },
		{ TranslationString("Radar", true), 0x8973A868 },
		{ TranslationString("Large Tarp", true), 0x6FA720A4 },
		{ TranslationString("Tree", true), 0xEDF5CD3C },
		{ TranslationString("Tugboat", true), 0xF20B1BDD },
		{ TranslationString("UFO", true), 0xB467C540 },
		{ TranslationString("Windmill", true), 0x745F3383 },
		{ TranslationString("Xmas Tree", true), 0x7121AC4 },
	};

	ScrollStruct<float> g_Precisions[] = {
		{ TranslationString(".0001", false), .0001f },
		{ TranslationString(".001", false), .001f },
		{ TranslationString(".01", false), .01f },
		{ TranslationString(".1", false), .1f },
		{ TranslationString("1", true), 1.f },
		{ TranslationString("2", true), 2.f },
		{ TranslationString("5", true), 5.f },
		{ TranslationString("10", true), 10.f },
		{ TranslationString("50", true), 50.f },
		{ TranslationString("100", true), 100.f }
	};

	ScrollStruct<std::pair<const char*, const char*>> g_Sounds[] = {
		{ TranslationString("Alien", true), { "SPAWN", "BARRY_01_SOUNDSET" } },
		{ TranslationString("Whistle", true), { "Franklin_Whistle_For_Chop", "SPEECH_RELATED_SOUNDS" } },
		{ TranslationString("EMP", true), { "EMP_Vehicle_Hum", "DLC_HEIST_BIOLAB_DELIVER_EMP_SOUNDS" } },
		{ TranslationString("Helicopter", true), { "Helicopter_Wind", "BASEJUMPS_SOUNDS" } },
		{ TranslationString("Scan", true), { "SCAN", "EPSILONISM_04_SOUNDSET" } },
		{ TranslationString("Leafblower", true), { "GARDENING_LEAFBLOWER_ANIM_TRIGGERED", "" } },
		{ TranslationString("Unlock", true), { "Bar_Unlock_And_Raise", "DLC_IND_ROLLERCOASTER_SOUNDS" } },
		{ TranslationString("Brakes", true), { "MOD_SHOP_BRAKES_ONESHOT", "" } },

		{ TranslationString("Carwash", true), { "SPRAY", "CARWASH_SOUNDS" } },
		{ TranslationString("Carwash 2", true), { "SPRAY_CAR", "CARWASH_SOUNDS" } },
		{ TranslationString("Carwash 3", true), { "DRYER", "CARWASH_SOUNDS" } },

		{ TranslationString("Keycard", true), { "Keycard_Success", "DLC_HEISTS_BIOLAB_FINALE_SOUNDS" } },
		{ TranslationString("Keycard 2", true), { "Keycard_Fail", "DLC_HEISTS_BIOLAB_FINALE_SOUNDS" } },

		{ TranslationString("Ringtone", true), { "Remote_Ring", "Phone_SoundSet_Michael" } },
		{ TranslationString("Ringtone 2", true), { "PED_PHONE_DIAL_01", "" } },

		{ TranslationString("Beep", true), { "Crate_Beeps", "MP_CRATE_DROP_SOUNDS" } },
		{ TranslationString("Beep 2", true), { "Crate_Collect", "MP_CRATE_DROP_SOUNDS" } },
		{ TranslationString("Endless Beep", true), { "CONTINUAL_BEEP", "EPSILONISM_04_SOUNDSET" } },
		{ TranslationString("Short Beep", true), { "IDLE_BEEP", "EPSILONISM_04_SOUNDSET" } },
		{ TranslationString("Long Beep", true), { "Beep_Green", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ TranslationString("Solo Fast Beep", true), { "Beep_Red", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ TranslationString("Confirm Beep", true), { "CONFIRM_BEEP", "HUD_MINI_GAME_SOUNDSET" } },

		{ TranslationString("5s Timer", true), { "5_Second_Timer", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ TranslationString("5s Timer 2", true), { "MP_5_SECOND_TIMER", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ TranslationString("Idle Timer", true), { "MP_IDLE_TIMER", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ TranslationString("Out of Bounds Timer", true), { "Out_Of_Bounds_Timer", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ TranslationString("Timer Stop", true), { "TIMER_STOP", "HUD_MINI_GAME_SOUNDSET" } },

		{ TranslationString("Pickup", true), { "PICK_UP", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ TranslationString("Pickup 2", true), { "PICK_UP_SOUND", "HUD_FRONTEND_CUSTOM_SOUNDSET" } },
		{ TranslationString("Pickup 3", true), { "PICKUP_WEAPON_SMOKEGRENADE", "HUD_FRONTEND_WEAPONS_PICKUPS_SOUNDSET" } },

		{ TranslationString("Silence", true), { "3_2_1_NON_RACE", "HUD_MINI_GAME_SOUNDSET" } },
		{ TranslationString("Silence 2", true), { "Airhorn", "DLC_TG_Running_Back_Sounds" } },

		{ TranslationString("Screen Flash", true), { "ScreenFlash", "MissionFailedSounds" } },
		{ TranslationString("Screen Flash 2", true), { "ScreenFlash", "WastedSounds" } },

		{ TranslationString("Click", true), { "Click", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ TranslationString("Click Fail", true), { "Click_Fail", "WEB_NAVIGATION_SOUNDS_PHONE" } },
		{ TranslationString("Click Special", true), { "Click_Special", "WEB_NAVIGATION_SOUNDS_PHONE" } },

		{ TranslationString("Nav Arrow Ahead", true), { "Nav_Arrow_Ahead", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ TranslationString("Nav Arrow Left", true), { "Nav_Arrow_Left", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ TranslationString("Nav Arrow Right", true), { "Nav_Arrow_Right", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },

		{ TranslationString("Checkpoint Missed", true), { "CHECKPOINT_MISSED", "HUD_MINI_GAME_SOUNDSET" } },
		{ TranslationString("Checkpoint Ahead", true), { "CHECKPOINT_AHEAD", "HUD_MINI_GAME_SOUNDSET" } },
		{ TranslationString("Checkpoint Perfect", true), { "CHECKPOINT_PERFECT", "HUD_MINI_GAME_SOUNDSET" } },
		{ TranslationString("Checkpoint Under Bridge", true), { "CHECKPOINT_UNDER_THE_BRIDGE", "HUD_MINI_GAME_SOUNDSET" } },

		{ TranslationString("Menu Select", true), { "Apt_Style_Purchase", "DLC_APT_Apartment_SoundSet" } },
		{ TranslationString("Menu Select 2", true), { "SELECT", "HUD_MINI_GAME_SOUNDSET" } },

		{ TranslationString("Hack Failed", true), { "Hack_Failed", "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS" } },
		{ TranslationString("Hack Success", true), { "Hack_Success", "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS" } },

		{ TranslationString("Pin Bad", true), { "Pin_Bad", "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS" } },
		{ TranslationString("Pin Button", true), { "PIN_BUTTON", "ATM_SOUNDS" } },
		{ TranslationString("Pin Good", true), { "Pin_Good", "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS" } },

		{ TranslationString("Tennis Match Point", true), { "TENNIS_MATCH_POINT", "HUD_AWARDS" } },
		{ TranslationString("Tennis Point Won", true), { "TENNIS_POINT_WON", "HUD_AWARDS" } },

		{ TranslationString("Start Squelch", true), { "Start_Squelch", "CB_RADIO_SFX" } },
		{ TranslationString("End Squelch", true), { "End_Squelch", "CB_RADIO_SFX" } },

		{ TranslationString("Garage Door Open", true), { "RAMP_UP", "TRUCK_RAMP_DOWN" } },
		{ TranslationString("1st Person Transition", true), { "1st_Person_Transition", "PLAYER_SWITCH_CUSTOM_SOUNDSET" } },
		{ TranslationString("Emphasis", true), { "3_2_1", "HUD_MINI_GAME_SOUNDSET" } },
		{ TranslationString("5s Warning", true), { "5_SEC_WARNING", "HUD_MINI_GAME_SOUNDSET" } },
		{ TranslationString("Notification", true), { "ATM_WINDOW", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ TranslationString("Challenge Unlocked", true), { "CHALLENGE_UNLOCKED", "HUD_AWARDS" } },
		{ TranslationString("Mission Success", true), { "BASE_JUMP_PASSED", "HUD_AWARDS" } },
		{ TranslationString("Wasted", true), { "Bed", "WastedSounds" } },
		{ TranslationString("Bus Pickup", true), { "Bus_Schedule_Pickup", "DLC_PRISON_BREAK_HEIST_SOUNDS" } },
		{ TranslationString("Taken Photo", true), { "Camera_Shoot", "Phone_Soundset_Franklin" } },
		{ TranslationString("Switching Characters", true), { "CHARACTER_SELECT", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ TranslationString("Close Window", true), { "CLOSE_WINDOW", "LESTER1A_SOUNDS" } },
		{ TranslationString("Crash", true), { "Crash", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ TranslationString("Delete", true), { "DELETE", "HUD_DEATHMATCH_SOUNDSET" } },
		{ TranslationString("Truck Rev", true), { "DiggerRevOneShot", "BulldozerDefault" } },
		{ TranslationString("Drill Pin Break", true), { "Drill_Pin_Break", "DLC_HEIST_FLEECA_SOUNDSET" } },
		{ TranslationString("Edit", true), { "EDIT", "HUD_DEATHMATCH_SOUNDSET" } },
		{ TranslationString("Error", true), { "ERROR", "HUD_AMMO_SHOP_SOUNDSET" } },
		{ TranslationString("Failure", true), { "Failure", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ TranslationString("Falling Crates", true), { "Falling_Crates", "EXILE_1" } },
		{ TranslationString("Car Breakdown", true), { "FAMILY_1_CAR_BREAKDOWN", "FAMILY1_BOAT" } },
		{ TranslationString("First Place", true), { "FIRST_PLACE", "HUD_MINI_GAME_SOUNDSET" } },
		{ TranslationString("Flight School Passed", true), { "FLIGHT_SCHOOL_LESSON_PASSED", "HUD_AWARDS" } },
		{ TranslationString("Focus In", true), { "FocusIn", "HintCamSounds" } },
		{ TranslationString("Go", true), { "GO", "HUD_MINI_GAME_SOUNDSET" } },
		{ TranslationString("Goal", true), { "Goal", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ TranslationString("Grab Parachute", true), { "Grab_Parachute", "BASEJUMPS_SOUNDS" } },
		{ TranslationString("Hang Up", true), { "Hang_Up", "Phone_SoundSet_Michael" } },
		{ TranslationString("Highlight Error", true), { "Highlight_Error", "DLC_HEIST_PLANNING_BOARD_SOUNDS" } },
		{ TranslationString("Hit", true), { "Hit", "RESPAWN_SOUNDSET" } },
		{ TranslationString("Hit 2", true), { "Hit_1", "LONG_PLAYER_SWITCH_SOUNDS" } },
		{ TranslationString("Hit Out", true), { "Hit_Out", "PLAYER_SWITCH_CUSTOM_SOUNDSET" } },
		{ TranslationString("Cash Counter Complete", true), { "LOCAL_PLYR_CASH_COUNTER_COMPLETE", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ TranslationString("Lose Match", true), { "LOOSE_MATCH", "HUD_MINI_GAME_SOUNDSET" } },
		{ TranslationString("Loser", true), { "LOSER", "HUD_AWARDS" } },
		{ TranslationString("Menu Accept", true), { "Menu_Accept", "Phone_SoundSet_Default" } },
		{ TranslationString("Mission Pass Notify", true), { "Mission_Pass_Notify", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ TranslationString("Award", true), { "MP_AWARD", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ TranslationString("Idle Kick", true), { "MP_IDLE_KICK", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ TranslationString("Rank Up", true), { "MP_RANK_UP", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ TranslationString("Wave Complete", true), { "MP_WAVE_COMPLETE", "HUD_FRONTEND_DEFAULT_SOUNDSET" } },
		{ TranslationString("On", true), { "ON", "NOIR_FILTER_SOUNDS" } },
		{ TranslationString("On Call Player Join", true), { "On_Call_Player_Join", "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS" } },
		{ TranslationString("Open Window", true), { "OPEN_WINDOW", "LESTER1A_SOUNDS" } },
		{ TranslationString("Other Text", true), { "OTHER_TEXT", "HUD_AWARDS" } },
		{ TranslationString("Player Collect", true), { "Player_Collect", "DLC_PILOT_MP_HUD_SOUNDS" } },
		{ TranslationString("Power Down", true), { "Power_Down", "DLC_HEIST_HACKING_SNAKE_SOUNDS" } },
		{ TranslationString("Pre Screen Stinger", true), { "Pre_Screen_Stinger", "DLC_HEISTS_FAILED_SCREEN_SOUNDS" } },
		{ TranslationString("Property Purchase", true), { "PROPERTY_PURCHASE", "HUD_AWARDS" } },
		{ TranslationString("Money Lost", true), { "PS2A_MONEY_LOST", "PALETO_SCORE_2A_BANK_SS" } },
		{ TranslationString("Put Away", true), { "Put_Away", "Phone_SoundSet_Michael" } },
		{ TranslationString("Round Ending", true), { "ROUND_ENDING_STINGER_CUSTOM", "CELEBRATION_SOUNDSET" } },
		{ TranslationString("Heartbeat", true), { "Short_Transition_In", "PLAYER_SWITCH_CUSTOM_SOUNDSET" } },
		{ TranslationString("Bomb Loading", true), { "STUN_COLLECT", "MINUTE_MAN_01_SOUNDSET" } },
	};
}